import assert from 'node:assert/strict';
import { createF1Service } from '../f1.mjs';
const race = { round: '16', date: '2026-10-04', time: '07:00:00Z', Circuit: { circuitId: 'sepang' } };
let now = Date.parse('2026-10-04T00:00:00Z'), offline = false, calls = [];
const service = createF1Service({ spacing: 0, clock: () => now, fetcher: async url => {
  calls.push(url);
  if (offline) throw new Error('offline');
  if (url.includes('api.jolpi.ca')) return Response.json({ MRData: { RaceTable: { Races: [race] } } });
  assert.equal(url, 'https://www.formula1.com/en/racing/2026/bahrain/circuit');
  return new Response('<img src="https://media.formula1.com/image/upload/c_fit,h_704/q_auto/v1740000001/common/f1/2026/track/2026trackkualalumpurdetailed.webp">');
} });
const [a,b] = await Promise.all([service.circuit(2026, '16'), service.circuit(2026, '16')]);
assert.match(a.data.imageUrl, /w_1600.*kualalumpurdetailed/);
assert.deepEqual(a.data.sectors, [[1,3],[4,9],[10,15]]);
assert.equal(a.data.imageUrl,b.data.imageUrl);
assert.equal(calls.length,2,'shared schedule and official map requests');
await service.circuit(2026,'16'); assert.equal(calls.length,2,'cached map metadata');
assert.equal((await service.circuit(2026,'17')).data,null,'missing round does not show another track');
await assert.rejects(()=>service.circuit(2026,'../16'),e=>e.status===400);
now+=16*60_000; offline=true;
const stale=await service.circuit(2026,'16');
assert.equal(stale.stale,true); assert.deepEqual(stale.data.sectors,[[1,3],[4,9],[10,15]]);
const fallback=createF1Service({spacing:0,fetcher:async url=>{
  if(url.includes('api.jolpi.ca'))return Response.json({MRData:{RaceTable:{Races:[race]}}});
  if(url.includes('formula1.com'))return new Response('<html>No map yet</html>');
  if(url.includes('/meetings?'))return Response.json([{meeting_name:'Bahrain Grand Prix',meeting_key:1308,circuit_key:12,date_start:'2026-10-02T00:00:00Z',date_end:'2026-10-04T09:00:00Z'}]);
  return Response.json({x:[0,100,200],y:[0,100,0],corners:[{number:1,trackPosition:{x:100,y:100}}]});
}});
assert.equal((await fallback.circuit(2026,'16')).data.corners[0].number,1,'geometric map remains available when official detailed map is missing');
console.log('PASS: official sector map, correct current track, shared cache, offline fallback, geometry fallback and validation');
const {default:sharp}=await import('sharp');
const input=await sharp(Buffer.from('<svg xmlns="http://www.w3.org/2000/svg" width="800" height="500"><path d="M150 250 L350 100 L650 250 L450 400 Z" fill="none" stroke="#e51b83" stroke-width="12"/></svg>')).png().toBuffer();
let imageCalls=0;
const imageService=createF1Service({spacing:0,fetcher:async url=>{
  if(url.includes('api.jolpi.ca'))return Response.json({MRData:{RaceTable:{Races:[race]}}});
  if(url.includes('www.formula1.com'))return new Response('<img src="https://media.formula1.com/image/upload/testdetailed.webp">');
  imageCalls++;return new Response(input,{headers:{'Content-Type':'image/png'}});
}});
const [mapA,mapB]=await Promise.all([imageService.circuitImage(2026,'16'),imageService.circuitImage(2026,'16')]);
const dimensions=await sharp(mapA).metadata();
assert(dimensions.width>400&&dimensions.width<800,'trim transparent margins while keeping entire track');
assert(dimensions.height>250&&dimensions.height<500);
assert.equal(dimensions.format,'webp');assert.deepEqual(mapA,mapB);assert.equal(imageCalls,1,'concurrent map image requests share rendering');
console.log('PASS: trimmed map retains circuit, optimized image and concurrent image caching');
const emailMap=await imageService.emailCircuitImage(2026,'16');
const emailMetadata=await sharp(emailMap).metadata();
assert.equal(emailMetadata.format,'png');assert.equal(emailMetadata.hasAlpha,false,'email map has an opaque background');
const pixel=await sharp(emailMap).extract({left:0,top:0,width:1,height:1}).raw().toBuffer();
assert.deepEqual([...pixel],[250,251,252],'transparent margin flattened to email surface');assert.equal(imageCalls,1,'email and website share map source');
console.log('PASS: email map uses opaque light PNG and shares website image cache');
