import assert from 'node:assert/strict';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { createF1Weather, summarizeWeather } from '../f1-weather.mjs';
import { createF1Service } from '../f1.mjs';
const race={round:'16',date:'2026-10-04',time:'07:00:00Z',FirstPractice:{date:'2026-10-02',time:'04:30:00Z'},Qualifying:{date:'2026-10-03',time:'08:00:00Z'},Circuit:{circuitId:'sepang',Location:{lat:'2.76083',long:'101.738'}}};
let now=Date.parse('2026-10-04T04:00:00Z'), calls=0, offline=false;
const hourlyTimes=Array.from({length:72},(_,i)=>`2026-10-0${2+Math.floor(i/24)}T${String(i%24).padStart(2,'0')}:00`);
const payload={timezone:'Asia/Kuala_Lumpur',daily:{time:['2026-10-02','2026-10-03','2026-10-04'],temperature_2m_min:[24,25,24],temperature_2m_max:[33,32,32],weather_code:[3,81,95],precipitation_probability_max:[95,95,95],precipitation_sum:[3,4,5],wind_gusts_10m_max:[20,25,45]},hourly:{time:hourlyTimes,temperature_2m:hourlyTimes.map(()=>30),precipitation_probability:hourlyTimes.map(t=>t.startsWith('2026-10-04T1')&&Number(t.slice(11,13))>=15&&Number(t.slice(11,13))<18?80:10),weather_code:hourlyTimes.map(()=>95),wind_gusts_10m:hourlyTimes.map(()=>45),precipitation:hourlyTimes.map(()=>0.5)}};
const report=summarizeWeather(race,payload,now);
assert.deepEqual(report.days.map(d=>d.date),['2026-10-02','2026-10-03','2026-10-04']);
assert.equal(report.days[0].kind,'past');assert.equal(report.days[2].kind,'forecast');
assert.equal(report.days[2].period,'15:00–18:00');assert.equal(report.days[2].rainChance,80,'use local race hours instead of all-day 95%');
assert.equal(report.days[2].rainMm,1.5);assert(report.days[2].impact.some(s=>s.includes('雷暴')));
const vegas={...race,date:'2026-11-22',time:'06:00:00Z',FirstPractice:{date:'2026-11-20',time:'00:30:00Z'},Qualifying:{date:'2026-11-21',time:'04:00:00Z'}};
const vegasReport=summarizeWeather(vegas,{timezone:'America/Los_Angeles',daily:{time:['2026-11-19','2026-11-20','2026-11-21']}},Date.parse('2026-11-21T01:00:00Z'));
assert.deepEqual(vegasReport.days.map(d=>d.date),['2026-11-19','2026-11-20','2026-11-21'],'Saturday-night race local dates differ from UTC calendar');
assert.equal(vegasReport.days[2].rainChance,null,'missing probability does not become 0%');
const dir=mkdtempSync(join(tmpdir(),'f1-weather-'));
const fetcher=async url=>{calls++;assert.equal(new URL(url).hostname,'api.open-meteo.com');if(offline)throw new Error('offline');return Response.json(payload);};
try{
const service=createF1Weather({dataDir:dir,clock:()=>now,fetcher});
const [a,b]=await Promise.all([service.weekend(race),service.weekend(race)]);
assert.equal(calls,1);assert.deepEqual(a.data,b.data);
now+=16*60_000;offline=true;
assert.equal((await service.weekend(race)).stale,true);assert.equal((await service.weekend(race)).data.days[2].rainChance,80);assert.equal(calls,2,'failure retries are backed off');
const restored=createF1Weather({dataDir:dir,clock:()=>now,fetcher});assert.equal((await restored.weekend(race)).data.days[2].rainChance,80,'disk cache survives restart');
assert.equal((await service.weekend({...race,date:'2026-12-31'})).reason,'forecast_pending');
assert.equal((await service.weekend({...race,date:'2026-09-01'})).reason,'past_weekend');
assert.equal((await service.weekend({...race,Circuit:{}})).reason,'coordinates_missing');
const invalid=createF1Weather({fetcher:async()=>Response.json({timezone:'broken',daily:{time:[]}}),clock:()=>now});assert.equal((await invalid.weekend(race)).unavailable,true,'reject invalid timezone');
const f1=createF1Service({spacing:0,clock:()=>now,fetcher:async url=>url.includes('api.open-meteo.com')?new Response('',{status:429}):Response.json({MRData:{total:'1',RaceTable:{Races:[race]}}})});
assert.equal((await f1.weather(2026,'16')).unavailable,true);
assert.equal((await f1.race(2026,'16')).unavailable,false,'weather rate limit does not block F1 results');
const notes=await f1.notes(2026,'16');assert.equal(notes.automatic,true);assert.equal(notes.data.tyres,null,'no manually maintained fallback');
assert.equal((await f1.notes(2026,'17')).data,null,'never reuse another round’s editorial notes');
await assert.rejects(()=>f1.weather(2026,'../../16'),e=>e.status===400);
console.log('PASS: circuit coordinates, three local dates, race-hour forecast, past labels, missing values, cache/offline/rate limits, safe race-specific notes');
}finally{rmSync(dir,{recursive:true,force:true});}
